version: "3"
services:
  gateway:
    volumes:
      - ./gateway/sites-available/repo-master:/etc/nginx/sites-enabled/repo

  rsync:
    container_name: rsyncd
    build: ./rsync/
    volumes:
      - ./data/repository/:/var/www/repository/
      - ./data/website/html:/var/www/html/
      - ./data/website/docs:/var/www/docs
      - ./data/website/static:/var/www/static
      - ./rsync/rsyncd.conf:/etc/rsyncd.conf
    restart: unless-stopped
    ports:
     - "873:873"
    networks:
      main:
        ipv4_address: 172.18.10.8
  
  updater:
    container_name: updater
    build: ./updater/
    volumes:
      - ./data/repository/:/var/www/repository
    restart: unless-stopped
    command: /bin/bash /update.sh